package it.fantaenrico.client.entities;

public enum FootballTeam {
	
	ATALANTA,BOLOGNA,CAGLIARI,CATANIA,CESENA,CHIEVO,FIORENTINA,
	GENOA,INTER,JUVENTUS,LAZIO,LECCE,MILAN,NAPOLI,NOVARA,
	PALERMO,PARMA,ROMA,SIENA,UDINESE;

}
